' Gambas module file

'
' Traducción de programas.
' Interfaz de translate-shell para traducir programas completos de gambas y otras utilidades.
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

Public stxLocLang As New String[]
Public stxSysLangName As New String[]
Public stxSysLangDesc As New String[]
Public stxSysLangFamy As New String[]
Public stxSysLangAlph As New String[]

Public Sub main()

  ' Dim strLang As String
  Dim stxLang As New String[]
  Dim intL As Integer
  Dim strLang As String
  Dim strDesc As String
  Dim strFamy As String
  Dim strLan As String
  Dim strAlph As String
  Dim stxShort As New String[]

  strLang = Settings["Language", "es"]

  stxLocLang.Clear

  stxLocLang = Msys.LocaleSatat()

  Wait 0.1

  Select strLang
    Case "es"
      System.Language = "es_ES.UTF-8"
    Case "fr"
      System.Language = "fr_FR.UTF-8"
    Case "en"
      System.Language = "en_US.UTF-8"
    Case "eo"
      System.Language = "eo_US.UTF-8"
    Case "it"
      System.Language = "it_IT.UTF-8"
    Case Else
      System.Language = String.LCase(strLang) & "_" & String.UCase(strLang) & ".UTF-8"

  End Select

  'Comprobacion de la existencia de directorios y archivos locales

  If Exist(User.Home &/ "." & Application.Name) = False Then
    Mkdir User.Home &/ "." & Application.Name
  Endif

  Wait 0.1

  ' Verificacion de la existencia del archivo de gb.settings
  If Exist(User.Home &/ ".config/gambas3" &/ Application.Name & ".conf") = False Then
    Copy Application.Name & ".conf" To User.Home &/ ".config/gambas3" &/ Application.Name & ".conf"
  Endif

  ' Verificacion de la existencia del archivo de lista completa de idiomas
  If Exist(User.Home &/ "." & Application.Name &/ "lang.csv") = False Then
    Copy "lang.csv" To User.Home &/ "." & Application.Name &/ "lang.csv"
  Endif

  ' Verificacion de la existencia del archivo de lista corta de idiomas
  If Exist(User.Home &/ "." & Application.Name &/ "short.csv") = False Then
    'Comprobacion de los idiomas disponibles en el sistema
    stxLang.Clear
    stxSysLangName.Clear
    stxSysLangDesc.Clear
    stxSysLangFamy.Clear
    stxSysLangAlph.Clear
    stxShort.Clear

    stxLang = Split(File.Load(User.Home &/ "." & Application.Name &/ "lang.csv"), "\n")

    For intL = 0 To stxLang.Max
      If stxLang[intL] <> "" Then

        strLan = Split(stxLang[intL], ":")[0]
        strDesc = Split(stxLang[intL], ":")[2] & "[" & Split(stxLang[intL], ":")[3] & "]"
        strFamy = Split(stxLang[intL], ":")[4]
        strAlph = Split(stxLang[intL], ":")[5]

        If stxLocLang.Find(strLan) <> -1 Then
          'If Msys.PkgStat("language-pack-" & strLan) = True Then
          stxSysLangName.Add(strLan)
          stxSysLangDesc.Add(strDesc)
          stxSysLangFamy.Add(strFamy)
          stxSysLangAlph.Add(strAlph)

          stxShort.Add(stxLang[intL])

        Endif

      Endif
    Next

    File.Save(User.Home &/ "." & Application.Name &/ "short.csv", stxShort.Join("\n"))

  Else
    stxLang = Split(File.Load(User.Home &/ "." & Application.Name &/ "short.csv"), "\n")
    For intL = 0 To stxLang.Max
      If stxLang[intL] <> "" Then

        strLan = Split(stxLang[intL], ":")[0]
        strDesc = Split(stxLang[intL], ":")[2] & "[" & Split(stxLang[intL], ":")[3] & "]"
        strFamy = Split(stxLang[intL], ":")[4]
        strAlph = Split(stxLang[intL], ":")[5]

        'If Msys.PkgStat("language-pack-" & strLan) = True Then
        stxSysLangName.Add(strLan)
        stxSysLangDesc.Add(strDesc)
        stxSysLangFamy.Add(strFamy)
        stxSysLangAlph.Add(strAlph)

        'Endif
      Endif
    Next
  Endif

  FMain.ShowModal()

End
